// Package serverhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package serverhttp

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for ResponseStatusErrorCode.
const (
	Error ResponseStatusErrorCode = "error"
)

// Defines values for ResponseStatusOkCode.
const (
	Ok ResponseStatusOkCode = "ok"
)

// GenerateSpecServerHttpResponse200 defines model for GenerateSpecServerHttpResponse200.
type GenerateSpecServerHttpResponse200 struct {
	// Spec Содержимое спецификации
	Spec   []byte           `json:"spec"`
	Status ResponseStatusOk `json:"status"`
}

// GenerateSpecServerHttpResponse500 defines model for GenerateSpecServerHttpResponse500.
type GenerateSpecServerHttpResponse500 struct {
	Status ResponseStatusError `json:"status"`
}

// ResponseStatusError defines model for ResponseStatusError.
type ResponseStatusError struct {
	Code        ResponseStatusErrorCode `json:"code"`
	Description string                  `json:"description"`
}

// ResponseStatusErrorCode defines model for ResponseStatusError.Code.
type ResponseStatusErrorCode string

// ResponseStatusOk defines model for ResponseStatusOk.
type ResponseStatusOk struct {
	Code        ResponseStatusOkCode `json:"code"`
	Description string               `json:"description"`
}

// ResponseStatusOkCode defines model for ResponseStatusOk.Code.
type ResponseStatusOkCode string

// UploadSpecHttpRequest defines model for UploadSpecHttpRequest.
type UploadSpecHttpRequest struct {
	// Name Название приложения спецификация которого выгружается
	Name string `json:"name"`

	// Spec Содержимое спецификации
	Spec []byte `json:"spec"`
}

// UploadSpecHttpResponse200 defines model for UploadSpecHttpResponse200.
type UploadSpecHttpResponse200 struct {
	Status ResponseStatusOk `json:"status"`
}

// UploadSpecHttpResponse500 defines model for UploadSpecHttpResponse500.
type UploadSpecHttpResponse500 struct {
	Status ResponseStatusError `json:"status"`
}

// GenerateSpecServerHttpParams defines parameters for GenerateSpecServerHttp.
type GenerateSpecServerHttpParams struct {
	// Name Наименование сервера спецификации
	Name string `form:"name" json:"name"`
}

// UploadSpecHttpJSONRequestBody defines body for UploadSpecHttp for application/json ContentType.
type UploadSpecHttpJSONRequestBody = UploadSpecHttpRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v1/specs/)
	GenerateSpecServerHttp(ctx echo.Context, params GenerateSpecServerHttpParams) error

	// (POST /v1/specs/)
	UploadSpecHttp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GenerateSpecServerHttp converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateSpecServerHttp(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateSpecServerHttpParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GenerateSpecServerHttp(ctx, params)
	return err
}

// UploadSpecHttp converts echo context to params.
func (w *ServerInterfaceWrapper) UploadSpecHttp(ctx echo.Context) error {
	var err error

	ctx.Set(BearerScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadSpecHttp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/specs/", wrapper.GenerateSpecServerHttp)
	router.POST(baseURL+"/v1/specs/", wrapper.UploadSpecHttp)

}

type GenerateSpecServerHttpRequestObject struct {
	Params GenerateSpecServerHttpParams
}

type GenerateSpecServerHttpResponseObject interface {
	VisitGenerateSpecServerHttpResponse(w http.ResponseWriter) error
}

type GenerateSpecServerHttp200JSONResponse GenerateSpecServerHttpResponse200

func (response GenerateSpecServerHttp200JSONResponse) VisitGenerateSpecServerHttpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateSpecServerHttp500JSONResponse GenerateSpecServerHttpResponse500

func (response GenerateSpecServerHttp500JSONResponse) VisitGenerateSpecServerHttpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadSpecHttpRequestObject struct {
	Body *UploadSpecHttpJSONRequestBody
}

type UploadSpecHttpResponseObject interface {
	VisitUploadSpecHttpResponse(w http.ResponseWriter) error
}

type UploadSpecHttp200JSONResponse UploadSpecHttpResponse200

func (response UploadSpecHttp200JSONResponse) VisitUploadSpecHttpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UploadSpecHttp500JSONResponse UploadSpecHttpResponse500

func (response UploadSpecHttp500JSONResponse) VisitUploadSpecHttpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /v1/specs/)
	GenerateSpecServerHttp(ctx context.Context, request GenerateSpecServerHttpRequestObject) (GenerateSpecServerHttpResponseObject, error)

	// (POST /v1/specs/)
	UploadSpecHttp(ctx context.Context, request UploadSpecHttpRequestObject) (UploadSpecHttpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GenerateSpecServerHttp operation middleware
func (sh *strictHandler) GenerateSpecServerHttp(ctx echo.Context, params GenerateSpecServerHttpParams) error {
	var request GenerateSpecServerHttpRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateSpecServerHttp(ctx.Request().Context(), request.(GenerateSpecServerHttpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateSpecServerHttp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GenerateSpecServerHttpResponseObject); ok {
		return validResponse.VisitGenerateSpecServerHttpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UploadSpecHttp operation middleware
func (sh *strictHandler) UploadSpecHttp(ctx echo.Context) error {
	var request UploadSpecHttpRequestObject

	var body UploadSpecHttpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadSpecHttp(ctx.Request().Context(), request.(UploadSpecHttpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadSpecHttp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadSpecHttpResponseObject); ok {
		return validResponse.VisitUploadSpecHttpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RVzU4bSRB+lVHtHkeM2RWXue1Kqw3KgShWTsiHYVzAgD3d9PQgWWgkm0S5cEBKromi",
	"vMEEMFhAhleofqOoevwTm7HJD3FOHndXV31d9X1fH0Eo2lLEGOsE/CNIwl1sB/bzf4xRBRrrEsM6qkNU",
	"T7SWzzGRIk7wr1qNg6QSEpWOsDwtMeTfJiahiqSORAw+0Ecq6IL6pkuXNKBbKqjvmB7dUd+8poF5RQO6",
	"ppy/aQAubAvVDjT4sNXRCC7ojkTwIdEqincgcyHRgU5twT8VboMPf3iTW3jDK3gjpHUbvbEPWeaCwoM0",
	"UtgEf3OUxi1hN8aFxNYehpoLLW7BWmULfgDbf0oJNQ9eFa6q4/eQhKKJ/Itx2uZ8aMMaFf2cGtfR7P4M",
	"LJt2+szDEDf2H8Yn9pcG7oVsiaDJUy3neZBiou8jjIM2VtD5PeV0RWeU02caUN+hO9OlAd1QQZfU50Vz",
	"Ooff5tShayrMMRWmSwWdU+HQmTmhc9M1L+mScuqbY9Mzp5W8X4a8Zjpqe7BAIrOtXOQOjyrbbwfzu3TK",
	"E8MwVZHu1DlfWXgLA4Vq7LV8YLg0TrCrtYSMz0fxtii1EusgZIrOKgLoHVOGKWBOHLqgGyZfl3L6xDwz",
	"J47pOf88W3dYGjsYc5VIt7jMcIV3wYVDVEmZcXWlxs0UEuNARuDD3yu1lVVwQQZ6197BO1z1mBGJx/92",
	"UFew8q2VArNyxPx5nOQNjjsrox17fVtfBZxtvQn+HCu2oFTQRo0qAX+zUqusCcZSfKXZmZIL5BJxnoMU",
	"VQfcoSOMRDFhgVYpusPHs8qlGhxcUsk2cKgPHivGtnuBlK0otPf19pLS6yb5FnH04XfaUmm6MRtPecRr",
	"S4OxVg1jPdao4qDllCeckcIyF6RIqmj1ZmyWVzymnyPVtF8MJ4qJ/lc0O4/WmOrHpqIZ9IFyq9xb+wh0",
	"Wc9XlNvnpTA9yu9RLvuFtJpv7Euh03wr/w4aTQzYesPIejcbWSMrdzm8NI5UtcAHD7JG9iUAAP//TiAJ",
	"whULAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
